### ISSUE TITLE
No logentries on LinuxSystems

### ISSUE THREAD

**Issue by Gissmo** [Argonne-National-Laboratory/Pam-2man-Auth#1]
Hi,
great plugin - but under Debian and Ubuntu, there is no auth.logs for the second user.
Only this:
ubuntu sudo: PAM unable to resolve symbol: pam_sm_setcred

**Comment by thompsonm-ANL** [comment]
Hi Gissmo... we've been out for the holidays, but I will investigate and get back to you!

**Comment by thompsonm-ANL** [comment]
Apologies for the delay... logging should now be fairly verbose.
