### ISSUE TITLE
sudo-authorizers group ignored.

### ISSUE THREAD

**Issue by bonnedav** [Argonne-National-Laboratory/Pam-2man-Auth#7]
It does not actually check if the second user is a member of the sudo-authorizers group. It will let anyone authorize. I would help if I could but I do not know very much about PAM. Maybe I will lookup a tutorial  when I get the time. Other than that it works great! Thank you.

**Comment by thompsonm-ANL** [comment]
Apologies it took me so long to look at this.  This was a silly one.  The 2man_group file that the makefile was putting into /etc/2man needs to be in /etc/pam.d.  Should be fixed on a clean install.
