### ISSUE TITLE
RHEL/CentOS 7 based implementation

### ISSUE THREAD

**Issue by cdarcang1** [Argonne-National-Laboratory/Pam-2man-Auth#8]
The 2-man auth module doesn't seem to integrate well into rpm based distros like RHEL.  Noticed several @include lines that reference pam files that don't exist (i.e., common-auth, etc.)  Is this issue possibly on your development path?

**Comment by trustdarkness** [comment]
Apologies this took so long to look at.  It should work now, you'll want to do a clean uninstall and reinstall.  This will replace your /etc/pam.d/sudo file and make a backup in /etc/pam.d/sudo.bak.  I'm still doing some cleanup, but tests functional on fedora 23.  Please let me know if you have any further issues.
